name: Testing Stuff

on: [push]

jobs: 
  debug_stuff_i_guess:
    name: Debug stuff I guess?
    runs-on: macOS-latest
    
    steps:
    - name: Parse Swift Version
      run: |
        \[[ `swift -version` =~ ([0-9]+\.[0-9]+(\.[0-9]+)?) ]]
        echo "::set-output name=version::$BASH_REMATCH"
      id: parse_swift_version
    - name: Print Version
      run: echo ${{steps.parse_swift_version.outputs.version}}